// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SPMiner.Models
{
    public partial class Task
    {
        /// <summary>
        /// 資料編號
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// 社群上文章的Id
        /// </summary>
        public string TaskId { get; set; }
        /// <summary>
        /// 文章連結
        /// </summary>
        public string TaskUrl { get; set; }
        /// <summary>
        /// 執行次數
        /// </summary>
        public int TaskCount { get; set; }
        /// <summary>
        /// 售價
        /// </summary>
        public decimal TaskPrice { get; set; }
        /// <summary>
        /// 資料建立日期
        /// </summary>
        public DateTime CreateDate { get; set; }
        /// <summary>
        /// 資料建立人員編號
        /// </summary>
        public int Creator { get; set; }
        /// <summary>
        /// 資料異動日期
        /// </summary>
        public DateTime? EditDate { get; set; }
        /// <summary>
        /// 資料異動人員編號
        /// </summary>
        public int? Editor { get; set; }
        /// <summary>
        /// 資料狀態
        /// </summary>
        public int Status { get; set; }
    }
}